/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.szalai.microservices.common.schema;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Box extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 578126751267656372L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Box\",\"namespace\":\"com.szalai.microservices.common.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"sizeX\",\"type\":\"double\"},{\"name\":\"sizeY\",\"type\":\"double\"},{\"name\":\"sizeZ\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Box> ENCODER =
      new BinaryMessageEncoder<Box>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Box> DECODER =
      new BinaryMessageDecoder<Box>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Box> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Box> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Box>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Box to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Box from a ByteBuffer. */
  public static Box fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence id;
  @Deprecated public CharSequence label;
  @Deprecated public double sizeX;
  @Deprecated public double sizeY;
  @Deprecated public double sizeZ;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Box() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param label The new value for label
   * @param sizeX The new value for sizeX
   * @param sizeY The new value for sizeY
   * @param sizeZ The new value for sizeZ
   */
  public Box(CharSequence id, CharSequence label, Double sizeX, Double sizeY, Double sizeZ) {
    this.id = id;
    this.label = label;
    this.sizeX = sizeX;
    this.sizeY = sizeY;
    this.sizeZ = sizeZ;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return label;
    case 2: return sizeX;
    case 3: return sizeY;
    case 4: return sizeZ;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (CharSequence)value$; break;
    case 1: label = (CharSequence)value$; break;
    case 2: sizeX = (Double)value$; break;
    case 3: sizeY = (Double)value$; break;
    case 4: sizeZ = (Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'label' field.
   * @return The value of the 'label' field.
   */
  public CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'sizeX' field.
   * @return The value of the 'sizeX' field.
   */
  public Double getSizeX() {
    return sizeX;
  }

  /**
   * Sets the value of the 'sizeX' field.
   * @param value the value to set.
   */
  public void setSizeX(Double value) {
    this.sizeX = value;
  }

  /**
   * Gets the value of the 'sizeY' field.
   * @return The value of the 'sizeY' field.
   */
  public Double getSizeY() {
    return sizeY;
  }

  /**
   * Sets the value of the 'sizeY' field.
   * @param value the value to set.
   */
  public void setSizeY(Double value) {
    this.sizeY = value;
  }

  /**
   * Gets the value of the 'sizeZ' field.
   * @return The value of the 'sizeZ' field.
   */
  public Double getSizeZ() {
    return sizeZ;
  }

  /**
   * Sets the value of the 'sizeZ' field.
   * @param value the value to set.
   */
  public void setSizeZ(Double value) {
    this.sizeZ = value;
  }

  /**
   * Creates a new Box RecordBuilder.
   * @return A new Box RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Box RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Box RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new Box RecordBuilder by copying an existing Box instance.
   * @param other The existing instance to copy.
   * @return A new Box RecordBuilder
   */
  public static Builder newBuilder(Box other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for Box instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Box>
    implements org.apache.avro.data.RecordBuilder<Box> {

    private CharSequence id;
    private CharSequence label;
    private double sizeX;
    private double sizeY;
    private double sizeZ;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sizeX)) {
        this.sizeX = data().deepCopy(fields()[2].schema(), other.sizeX);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sizeY)) {
        this.sizeY = data().deepCopy(fields()[3].schema(), other.sizeY);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sizeZ)) {
        this.sizeZ = data().deepCopy(fields()[4].schema(), other.sizeZ);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Box instance
     * @param other The existing instance to copy.
     */
    private Builder(Box other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sizeX)) {
        this.sizeX = data().deepCopy(fields()[2].schema(), other.sizeX);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sizeY)) {
        this.sizeY = data().deepCopy(fields()[3].schema(), other.sizeY);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sizeZ)) {
        this.sizeZ = data().deepCopy(fields()[4].schema(), other.sizeZ);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public Builder setId(CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'label' field.
      * @return The value.
      */
    public CharSequence getLabel() {
      return label;
    }

    /**
      * Sets the value of the 'label' field.
      * @param value The value of 'label'.
      * @return This builder.
      */
    public Builder setLabel(CharSequence value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'label' field.
      * @return This builder.
      */
    public Builder clearLabel() {
      label = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sizeX' field.
      * @return The value.
      */
    public Double getSizeX() {
      return sizeX;
    }

    /**
      * Sets the value of the 'sizeX' field.
      * @param value The value of 'sizeX'.
      * @return This builder.
      */
    public Builder setSizeX(double value) {
      validate(fields()[2], value);
      this.sizeX = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sizeX' field has been set.
      * @return True if the 'sizeX' field has been set, false otherwise.
      */
    public boolean hasSizeX() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sizeX' field.
      * @return This builder.
      */
    public Builder clearSizeX() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sizeY' field.
      * @return The value.
      */
    public Double getSizeY() {
      return sizeY;
    }

    /**
      * Sets the value of the 'sizeY' field.
      * @param value The value of 'sizeY'.
      * @return This builder.
      */
    public Builder setSizeY(double value) {
      validate(fields()[3], value);
      this.sizeY = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sizeY' field has been set.
      * @return True if the 'sizeY' field has been set, false otherwise.
      */
    public boolean hasSizeY() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sizeY' field.
      * @return This builder.
      */
    public Builder clearSizeY() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'sizeZ' field.
      * @return The value.
      */
    public Double getSizeZ() {
      return sizeZ;
    }

    /**
      * Sets the value of the 'sizeZ' field.
      * @param value The value of 'sizeZ'.
      * @return This builder.
      */
    public Builder setSizeZ(double value) {
      validate(fields()[4], value);
      this.sizeZ = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'sizeZ' field has been set.
      * @return True if the 'sizeZ' field has been set, false otherwise.
      */
    public boolean hasSizeZ() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'sizeZ' field.
      * @return This builder.
      */
    public Builder clearSizeZ() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Box build() {
      try {
        Box record = new Box();
        record.id = fieldSetFlags()[0] ? this.id : (CharSequence) defaultValue(fields()[0]);
        record.label = fieldSetFlags()[1] ? this.label : (CharSequence) defaultValue(fields()[1]);
        record.sizeX = fieldSetFlags()[2] ? this.sizeX : (Double) defaultValue(fields()[2]);
        record.sizeY = fieldSetFlags()[3] ? this.sizeY : (Double) defaultValue(fields()[3]);
        record.sizeZ = fieldSetFlags()[4] ? this.sizeZ : (Double) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Box>
    WRITER$ = (org.apache.avro.io.DatumWriter<Box>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Box>
    READER$ = (org.apache.avro.io.DatumReader<Box>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
